Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/12/2022
Var

cont: inteiro
idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 1 ate 4 faca
   escreval ("Digite a idade: ", cont)
       leia (idade)
   escreval ("Idade Digitada: ", idade)

fimpara

Fimalgoritmo