Algoritmo "semnome"
// Faça um algoritmo que gere o Fatorial de um número digitado pelo usuário.
//Obs.: fatorial(5) = 1*2*3*4*5

Var
// Criar uma variavel fatorial
fatorial: inteiro
n: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite um numero:")
leia (n)
para fatorial de 1 ate n faca
escreval (fatorial <- )



fimpara

Fimalgoritmo